#!/bin/bash
# Build DTO
dtc -O dtb -o SPI-TEST-00A0.dtbo -b 0 -@ SPI-TEST-00A0.dts

# Install DTO
sudo cp SPI-TEST-00A0.dtbo /lib/firmware

# Activate PRU hardware
sudo sh -c "echo SPI-TEST > $SLOTS"
